### ISSUE TITLE
TypeError: Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by marcelklehr** [vidigami/backbone-rest#11]
```js
var Backbone = require('backbone')
var RestController = require('backbone-rest');
var express = require('express')
var static  = require('express-static');

var app = express()

app.use(static(__dirname));


var Device = Backbone.Model.extend({
  url: '/devices'
, database_url: 'sqlite3://'
, schema: {
    location: function() { return ['belongsTo', Location]; }
  , product: function() { return ['belongsTo', Product]; }
  , retailer: function() { return ['belongsTo', Retailer]; }
  , serialNumber: 'String'
  , lranr: 'String'
  , price: 'String'
  , acquisitionDate: 'String'
  , comment: 'String'
  }
})
Device.prototype.sync = require('backbone-sql').sync(Device)
new RestController(app, {model_type: Device, route: '/devices'})

// - snap -
```

produces

```
code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:9210
            if (!_.isFunction(reverse_model_type.schema)) {
                                                ^
TypeError: Cannot read property 'schema' of undefined
    at One.module.exports.Relation._findOrGenerateReverseRelation (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:9210:42)
    at One.module.exports.One.initialize (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:6385:35)
    at Schema.module.exports.Schema.initialize (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:2268:17)
    at SqlSync.initialize (code\node_modules\backbone-sql\lib\sync.js:84:19)
    at type.sync.sync_fn [as sync] (code\node_modules\backbone-sql\lib\sync.js:248:12)
    at Function.model_type.schema.model_type.schema (code\node_modules\backbone-sql\node_modules\backbone-orm\backbone-orm.js:5824:34)
    at JoinTableControllerSingleton.generateByOptions (code\node_modules\backbone-rest\lib\lib\join_table_controller_singleton.js:35:35)
    at new RESTController (code\node_modules\backbone-rest\lib\rest_controller.js:47:36)
    at Object.<anonymous> (code\node\index.js:26:38)
    at Module._compile (module.js:456:26)
```

Am I missing something obvious?

Thanks for your help!

**Comment by kmalakoff** [comment]
I think this might be a problem with your url. It should not have database_url and be of the Backbone form like `urlRoot: 'sqlite3://devices'` (models) or `url: 'sqlite3://devices'` (collections)

**Comment by marcelklehr** [comment]
Seems like that fixes things on my server side code for now :) thanks

**Comment by marcelklehr** [comment]
I get this error again.

I reverse engineered backbone-sql to find out the exact form of the urlRoot property and I came up with this:
```
var Backbone = require('backbone')
var BackboneORM = require('backbone-orm')
var RestController = require('backbone-rest');
var express = require('express')
var static  = require('express-static');

var app = express()

app.use(static(__dirname+'/..'));

app.listen(3000)

var Device = Backbone.Model.extend({
  urlRoot: 'sqlite3://db.sqlite/devices'
, schema: {
    location: function() { return ['belongsTo', Location]; }
  , product: function() { return ['belongsTo', Product]; }
  , retailer: function() { return ['belongsTo', Retailer]; }
  , serialNumber: 'String'
  , lranr: 'String'
  , price: 'String'
  , acquisitionDate: 'String'
  , comment: 'String'
  }
})
Device.prototype.sync = require('backbone-sql').sync(Device)
Device.db().ensureSchema(console.log)
new RestController(app, {model_type: Device, route: '/devices'})
// ...
```

**Comment by marcelklehr** [comment]
Ah, I think I found the bug. I was calling ensureSchema, before defining the other Models...

**Comment by kmalakoff** [comment]
I'm sorry about this...I've added an issue to backbone-sql to document this: https://github.com/vidigami/backbone-sql/issues/19
